# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: DND 3rd Edition Angular Build and Deploy

on:
  push:
    paths:
      - 'webapp/**'
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout Node Repository
      uses: actions/checkout@v3
      with:
        node-version: 18
        cache: 'npm'

    - name: Install Dependencies
      working-directory: ./webapp
      run: npm ci --force

    - name: Build Angular App
      working-directory: ./webapp
      run: npm run build --prod --if-present

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Deploy to S3
      working-directory: ./webapp
      run: aws s3 sync ./dist/webapp/browser s3://dnd3rd.scritch.ninja --delete
