name: DND 3rd Edition API Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
#    env:
#      DND3RD_LAMBDA_ARN: ${{ env.DND3RD_LAMBDA_ARN }}
#      COGNITO_ISSUER: ${{ env.COGNITO_ISSUER }}
#      COGNITO_AUDIENCE_1: ${{ env.COGNITO_AUDIENCE_1}
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Replace Swagger.yaml Fields
        working-directory: ./docs/deploy
#        run: sh ./replaceStringInYaml.sh
        run: echo ${{ vars.COGNITO_AUDIENCE_1 }}

      - name: Deploy API
        working-directory: ./docs/deploy
        run: sh ./deploy.sh