name: DND 3rd Edition Lambda Python SAM Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
#      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      # sam build
      - name: ZIP Lambda
        working-directory: ./lambda
        run: zip -r lambda.zip ./dnd3rd-lambda
#        run: sam build --use-container --template-file ./template.yaml

      # sam deploy
      - name: SAM Deploy
        working-directory: ./lambda
        run: aws lambda update-function-code --function-name=dnd3rd-DND3rdScritchNinja-eDkEfBBxC23A --zip-file=fileb://lambda.zip
#        run: sam deploy --config-file ./samconfig.toml --no-confirm-changeset