name: DND 3rd Edition Lambda Python SAM Deploy

on:
  push:
    paths:
      - 'lambda/**'
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      LAMBDA_FUNCTION_NAME: ${{ vars.DND3RD_LAMBDA_ARN }}
      REDIS_SECRETS_NAME: ${{ vars.REDIS_SECRETS_NAME}}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      DB_NAME: ${{ vars.DB_NAME }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: ZIP Lambda
        working-directory: ./lambda/dnd3rd-lambda
        run: zip -r lambdaToDeploy.zip *

      - name: Deploy Lambda
        working-directory: ./lambda
        run: sh ./deploy.sh